import React, { useState, useCallback, useMemo } from 'react';
import {
  ReactFlow,
  MiniMap,
  Controls,
  Background,
  useNodesState,
  useEdgesState,
  addEdge,
  BackgroundVariant,
  ReactFlowProvider,
  useReactFlow,
  type Connection,
  type Edge,
  type Node
} from '@xyflow/react';

import { Sidebar } from '../components/Sidebar';
import { NodeInspector } from '../components/NodeInspector';
import { AgentNode, StartNode, OutputNode } from '../components/nodes/AgentNode';
import type { Agent } from '../types/agent';
import { Play, Save, CheckCircle2, Bot, Sparkles, X } from 'lucide-react';

interface BuildPipelineViewProps {
  agents?: Agent[];
}

const BuildPipelineContent: React.FC<BuildPipelineViewProps> = ({ agents = [] }) => {
  const [pipelineName, setPipelineName] = useState('Untitled Pipeline');
  const [nodes, setNodes, onNodesChange] = useNodesState<Node>([]);
  const [edges, setEdges, onEdgesChange] = useEdgesState<Edge>([]);
  const [selectedNodeId, setSelectedNodeId] = useState<string | null>(null);
  
  const [isDraggingOverCanvas, setIsDraggingOverCanvas] = useState(false);
  
  // Execution state
  const [isRunModalOpen, setIsRunModalOpen] = useState(false);
  const [runInput, setRunInput] = useState('');
  const [isExecuting, setIsExecuting] = useState(false);
  const [executionResult, setExecutionResult] = useState<string | null>(null);

  const { screenToFlowPosition } = useReactFlow();

  const nodeTypes = useMemo(
    () => ({
      agentNode: AgentNode,
      startNode: StartNode,
      outputNode: OutputNode
    }),
    []
  );

  const onConnect = useCallback(
    (params: Edge | Connection) =>
      setEdges((eds) => addEdge({ ...params, animated: true, style: { stroke: '#94a3b8', strokeWidth: 2 } } as Edge, eds)),
    [setEdges]
  );

  const onNodeClick = useCallback((_: React.MouseEvent, node: Node) => {
    setSelectedNodeId(node.id);
  }, []);

  const onPaneClick = useCallback(() => {
    setSelectedNodeId(null);
  }, []);

  const onDragOver = useCallback((event: React.DragEvent) => {
    event.preventDefault();
    event.dataTransfer.dropEffect = 'move';
    if (!isDraggingOverCanvas) setIsDraggingOverCanvas(true);
  }, [isDraggingOverCanvas]);

  const onDragLeave = useCallback(() => {
    setIsDraggingOverCanvas(false);
  }, []);

  const onDrop = useCallback(
    (event: React.DragEvent) => {
      event.preventDefault();
      setIsDraggingOverCanvas(false);

      const dataString = event.dataTransfer.getData('application/reactflow');
      if (!dataString) return;

      try {
        const { type, data } = JSON.parse(dataString);
        const position = screenToFlowPosition({
          x: event.clientX,
          y: event.clientY
        });

        const id = `node_${Date.now()}`;
        const newNode: Node = {
          id,
          type,
          position,
          data: { ...data, status: 'idle' }
        };

        setNodes((nds) => [...nds, newNode]);
        setSelectedNodeId(id);
      } catch (err) {
        console.error('Failed to parse dropped node data:', err);
      }
    },
    [screenToFlowPosition, setNodes]
  );

  const handleDeleteNode = useCallback(
    (nodeId: string) => {
      setNodes((nds) => nds.filter((node) => node.id !== nodeId));
      setEdges((eds) => eds.filter((edge) => edge.source !== nodeId && edge.target !== nodeId));
      if (selectedNodeId === nodeId) {
        setSelectedNodeId(null);
      }
    },
    [setNodes, setEdges, selectedNodeId]
  );

  const handleSave = () => {
    // In a real app, this would save to the backend.
    alert('Pipeline saved successfully!');
  };

  const handleRunClick = () => {
    // Validate pipeline
    if (nodes.length === 0) {
      alert('Cannot run an empty pipeline.');
      return;
    }
    
    const hasStart = nodes.some(n => n.type === 'startNode');
    if (!hasStart) {
      alert('Pipeline needs a "User Input" start node.');
      return;
    }

    setIsRunModalOpen(true);
    setExecutionResult(null);
  };

  const executePipeline = async () => {
    setIsExecuting(true);
    
    // Simulate execution step by step
    const agentNodes = nodes.filter(n => n.type === 'agentNode');
    
    for (const node of agentNodes) {
      setNodes(nds => nds.map(n => n.id === node.id ? { ...n, data: { ...n.data, status: 'running' } } : n));
      await new Promise(r => setTimeout(r, 1500)); // fake delay
      setNodes(nds => nds.map(n => n.id === node.id ? { ...n, data: { ...n.data, status: 'success' } } : n));
    }
    
    await new Promise(r => setTimeout(r, 500));
    setExecutionResult("This is a simulated final output generated by the pipeline agents based on your input: " + runInput);
    setIsExecuting(false);
  };

  const resetExecution = () => {
    setNodes(nds => nds.map(n => ({ ...n, data: { ...n.data, status: 'idle' } })));
    setIsRunModalOpen(false);
    setRunInput('');
    setExecutionResult(null);
  };

  const selectedNode = useMemo(() => {
    return nodes.find((n) => n.id === selectedNodeId) || null;
  }, [nodes, selectedNodeId]);

  return (
    <div className="flex flex-col h-full w-full bg-slate-50 overflow-hidden font-sans">
      {/* Top Header */}
      <header className="h-16 bg-white border-b border-slate-200 px-6 flex items-center justify-between shrink-0 shadow-sm z-30 relative">
        <div className="flex flex-col justify-center">
           <div className="flex items-center gap-2">
             <h1 className="text-lg font-bold text-slate-900 tracking-tight">Build Pipeline</h1>
             <span className="text-[10px] font-bold tracking-wider uppercase bg-blue-50 text-blue-600 px-2 py-0.5 rounded-full border border-blue-200">
               Low-Code
             </span>
           </div>
           <p className="text-xs text-slate-500">Compose your existing AI agents into reusable workflows.</p>
        </div>

        <div className="flex items-center gap-4">
           <div className="flex flex-col items-end">
             <span className="text-[10px] font-semibold text-slate-400 uppercase tracking-wider mb-0.5">Pipeline Name</span>
             <span className="text-sm font-bold text-slate-800">{pipelineName}</span>
           </div>

           <div className="h-8 w-px bg-slate-200 mx-2"></div>

           <button 
             onClick={handleSave}
             className="flex items-center gap-1.5 px-4 py-2 bg-white hover:bg-slate-50 border border-slate-200 rounded-lg text-sm font-semibold text-slate-700 shadow-sm transition active:scale-95"
           >
             <Save className="w-4 h-4 text-slate-500" />
             Save
           </button>
           
           <button 
             onClick={handleRunClick}
             className="flex items-center gap-1.5 px-4 py-2 bg-emerald-600 hover:bg-emerald-700 text-white rounded-lg text-sm font-semibold shadow-sm transition active:scale-95"
           >
             <Play className="w-4 h-4 fill-current" />
             Run Pipeline
           </button>
        </div>
      </header>

      <div className="flex-1 flex overflow-hidden relative">
        <Sidebar agents={agents} />

        <div
          className={`flex-1 h-full relative transition-colors ${
            isDraggingOverCanvas ? 'bg-blue-50' : ''
          }`}
          onDragOver={onDragOver}
          onDragLeave={onDragLeave}
          onDrop={onDrop}
        >
          {nodes.length === 0 && (
            <div className="absolute inset-0 flex flex-col items-center justify-center pointer-events-none z-10 opacity-70">
              <div className="w-16 h-16 bg-white border-2 border-dashed border-slate-300 rounded-full flex items-center justify-center mb-4 shadow-sm">
                <Bot className="w-8 h-8 text-slate-300" />
              </div>
              <h2 className="text-xl font-bold text-slate-700 mb-2">Build your first agent workflow</h2>
              <p className="text-sm text-slate-500 max-w-sm text-center">
                Drag <b>User Input</b>, some <b>Agents</b>, and <b>Final Output</b> from the left sidebar here to get started.
              </p>
            </div>
          )}

          <ReactFlow
            nodes={nodes}
            edges={edges}
            onNodesChange={onNodesChange}
            onEdgesChange={onEdgesChange}
            onConnect={onConnect}
            onNodeClick={onNodeClick}
            onPaneClick={onPaneClick}
            nodeTypes={nodeTypes}
            fitView
            className="custom-scrollbar"
            minZoom={0.2}
            maxZoom={1.5}
            defaultEdgeOptions={{
              animated: true,
              style: { stroke: '#94a3b8', strokeWidth: 2 }
            }}
          >
            <Background color="#cbd5e1" gap={24} size={1.5} variant={BackgroundVariant.Dots} />
            <Controls className="bg-white border-slate-200 fill-slate-600 shadow-sm rounded-lg overflow-hidden m-4" />
            <MiniMap
              className="rounded-lg shadow-sm border border-slate-200 overflow-hidden m-4"
              nodeColor={(n) => {
                if (n.type === 'agentNode') return '#3b82f6';
                if (n.type === 'startNode') return '#10b981';
                if (n.type === 'outputNode') return '#6366f1';
                return '#cbd5e1';
              }}
              maskColor="rgba(248, 250, 252, 0.8)"
            />
          </ReactFlow>

          {isDraggingOverCanvas && (
            <div className="absolute inset-0 border-2 border-dashed border-blue-500 bg-blue-50/50 pointer-events-none flex items-center justify-center z-20">
              <span className="text-sm font-bold text-blue-700 bg-white px-6 py-3 rounded-xl shadow-lg flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-blue-500" />
                Drop to Add to Pipeline
              </span>
            </div>
          )}
        </div>

        <NodeInspector
          selectedNode={selectedNode}
          pipelineName={pipelineName}
          setPipelineName={setPipelineName}
          nodesCount={nodes.length}
          edgesCount={edges.length}
          onClose={() => setSelectedNodeId(null)}
          onDeleteNode={handleDeleteNode}
        />
      </div>

      {/* Run Modal Overlay */}
      {isRunModalOpen && (
        <div className="fixed inset-0 bg-slate-900/40 backdrop-blur-sm z-50 flex items-center justify-center p-6 animate-in fade-in duration-200">
          <div className="bg-white rounded-2xl shadow-2xl w-full max-w-2xl overflow-hidden flex flex-col max-h-full">
            <div className="px-6 py-4 border-b border-slate-100 flex items-center justify-between bg-slate-50">
              <div className="flex items-center gap-3">
                <div className="w-8 h-8 rounded-full bg-emerald-100 text-emerald-600 flex items-center justify-center">
                  <Play className="w-4 h-4 fill-current" />
                </div>
                <div>
                  <h3 className="text-base font-bold text-slate-900">Run Pipeline</h3>
                  <p className="text-xs text-slate-500">{pipelineName}</p>
                </div>
              </div>
              {!isExecuting && (
                <button onClick={resetExecution} className="p-2 text-slate-400 hover:text-slate-600 rounded-lg hover:bg-slate-200 transition">
                  <X className="w-5 h-5" />
                </button>
              )}
            </div>

            <div className="p-6 overflow-y-auto custom-scrollbar flex-1">
              {!isExecuting && !executionResult ? (
                <div className="space-y-4">
                  <label className="block text-sm font-semibold text-slate-700">
                    Initial Input
                  </label>
                  <textarea
                    rows={4}
                    value={runInput}
                    onChange={(e) => setRunInput(e.target.value)}
                    placeholder="Enter the starting input for this pipeline..."
                    className="w-full bg-slate-50 border border-slate-200 rounded-xl p-4 text-slate-900 focus:outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20 transition resize-none"
                  />
                </div>
              ) : (
                <div className="space-y-8">
                  {/* Execution Steps */}
                  <div className="space-y-4">
                    <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider">Execution Steps</h4>
                    <div className="space-y-3">
                      {nodes.filter(n => n.type === 'agentNode').map((node, i) => {
                        const agent = node.data.agent as Agent;
                        const status = node.data.status as string;
                        return (
                          <div key={node.id} className="flex items-center gap-4">
                            <div className="w-6 h-6 rounded-full bg-slate-100 border border-slate-200 flex items-center justify-center text-[10px] font-bold text-slate-500 shrink-0">
                              {i + 1}
                            </div>
                            <div className="flex-1 bg-white border border-slate-200 p-3 rounded-lg flex items-center justify-between">
                              <span className="text-sm font-semibold text-slate-800">{agent?.name || 'Agent'}</span>
                              {status === 'running' && <div className="w-4 h-4 rounded-full border-2 border-blue-500 border-t-transparent animate-spin" />}
                              {status === 'success' && <CheckCircle2 className="w-5 h-5 text-emerald-500" />}
                              {status === 'idle' && <span className="w-2 h-2 rounded-full bg-slate-200"></span>}
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  </div>

                  {/* Final Output */}
                  {executionResult && (
                    <div className="space-y-4 animate-in fade-in slide-in-from-bottom-4 duration-500">
                      <h4 className="text-xs font-bold text-indigo-400 uppercase tracking-wider flex items-center gap-2">
                        <Sparkles className="w-4 h-4" /> Final Output
                      </h4>
                      <div className="bg-indigo-50 border border-indigo-100 rounded-xl p-5 text-indigo-900 text-sm leading-relaxed shadow-sm">
                        {executionResult}
                      </div>
                    </div>
                  )}
                </div>
              )}
            </div>

            <div className="px-6 py-4 bg-slate-50 border-t border-slate-100 flex items-center justify-end gap-3">
               {!isExecuting && !executionResult ? (
                 <>
                   <button onClick={resetExecution} className="px-4 py-2 text-sm font-semibold text-slate-600 hover:text-slate-900 transition">
                     Cancel
                   </button>
                   <button 
                     onClick={executePipeline}
                     disabled={!runInput.trim()}
                     className="px-6 py-2 bg-blue-600 hover:bg-blue-700 disabled:opacity-50 disabled:hover:bg-blue-600 text-white rounded-lg text-sm font-semibold shadow-sm transition active:scale-95 flex items-center gap-2"
                   >
                     Run
                     <Play className="w-4 h-4 fill-current" />
                   </button>
                 </>
               ) : executionResult ? (
                 <button 
                   onClick={resetExecution}
                   className="px-6 py-2 bg-slate-900 hover:bg-slate-800 text-white rounded-lg text-sm font-semibold shadow-sm transition active:scale-95"
                 >
                   Close
                 </button>
               ) : (
                 <button 
                   disabled
                   className="px-6 py-2 bg-blue-400 text-white rounded-lg text-sm font-semibold shadow-sm flex items-center gap-2 opacity-70"
                 >
                   <div className="w-4 h-4 rounded-full border-2 border-white border-t-transparent animate-spin" />
                   Running...
                 </button>
               )}
            </div>
          </div>
        </div>
      )}

    </div>
  );
};

export const BuildPipelineView: React.FC<BuildPipelineViewProps> = (props) => {
  return (
    <ReactFlowProvider>
      <BuildPipelineContent {...props} />
    </ReactFlowProvider>
  );
};
